#!python
import importlib
from typing import cast

import typer

from euler.solver import Solver

app = typer.Typer(
    help="Project Euler solutions",
    add_completion=False,
)


@app.command()
def solve(
    problem: int = typer.Option(..., help="Problem number"),
    test: bool = typer.Option(False, help="Run against the test case, if available"),
) -> None:
    """
    Run a solution.
    """
    try:
        solution = cast(Solver, importlib.import_module(f"euler.solutions.{problem}"))
        solution.test() if test else solution.run()
    except ModuleNotFoundError:
        print(f"No solution for problem #{problem}!")


if __name__ == "__main__":
    app()
